version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "${DB_POSTGRES_PATH}:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    expose:
      - "5432"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db