version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "${DB_POSTGRES_PATH}:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    expose:
      - "5432"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web_server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db

  web_client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - db
      - web_server

  connector:
    build:
      context: .
      dockerfile: connector.Dockerfile
    depends_on:
      - db