// Code generated by protoc-gen-go. DO NOT EDIT.
// source: procedure/product/product.proto

/*
Package product is a generated protocol buffer package.

It is generated from these files:
	procedure/product/product.proto

It has these top-level messages:
	ProductRequest
	ProductResponse
*/
package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductRequest struct {
	Code  string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Price uint64 `protobuf:"varint,17,opt,name=price" json:"price,omitempty"`
}

func (m *ProductRequest) Reset()                    { *m = ProductRequest{} }
func (m *ProductRequest) String() string            { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()               {}
func (*ProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProductRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ProductRequest) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ProductResponse struct {
	Code  string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Price uint64 `protobuf:"varint,17,opt,name=price" json:"price,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProductResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ProductResponse) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*ProductRequest)(nil), "product.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "product.ProductResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProductActor service

type ProductActorClient interface {
	Create(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type productActorClient struct {
	cc *grpc.ClientConn
}

func NewProductActorClient(cc *grpc.ClientConn) ProductActorClient {
	return &productActorClient{cc}
}

func (c *productActorClient) Create(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/product.ProductActor/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductActor service

type ProductActorServer interface {
	Create(context.Context, *ProductRequest) (*ProductResponse, error)
}

func RegisterProductActorServer(s *grpc.Server, srv ProductActorServer) {
	s.RegisterService(&_ProductActor_serviceDesc, srv)
}

func _ProductActor_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductActorServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductActor/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductActorServer).Create(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductActor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductActor",
	HandlerType: (*ProductActorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductActor_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "procedure/product/product.proto",
}

func init() { proto.RegisterFile("procedure/product/product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x4f,
	0x4e, 0x4d, 0x29, 0x2d, 0x4a, 0xd5, 0x2f, 0x28, 0xca, 0x4f, 0x29, 0x4d, 0x2e, 0x81, 0xd1, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae, 0x92, 0x15, 0x17, 0x5f, 0x00, 0x84, 0x19,
	0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x9c, 0x9f, 0x92, 0x2a, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0x16, 0x14, 0x65, 0x26, 0xa7,
	0x4a, 0x08, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x4a, 0xd6, 0x5c, 0xfc, 0x70, 0xbd, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xc4, 0x6b, 0x36, 0xf2, 0xe5, 0xe2, 0x81, 0x6a, 0x76, 0x4c, 0x2e,
	0xc9, 0x2f, 0x12, 0xb2, 0xe5, 0x62, 0x73, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x15, 0x12, 0xd7, 0x83,
	0xb9, 0x15, 0xd5, 0x65, 0x52, 0x12, 0x98, 0x12, 0x10, 0x6b, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xfe,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xff, 0xe5, 0x6a, 0xfa, 0x00, 0x00, 0x00,
}
